- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: starting and enabling mysql
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: yes

- name: install botocore and boto3
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - boto3
  - botocore

- name: set up root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass $MYSQL_ROOT_PASSWORD